/**************************************************************\
Edition:
##  @date 30/07/2026 by @author Tsukini

File Name:
##  @file ExceptionDefine.hpp

File Description:
##  Definition of the error code&message
\**************************************************************/

#ifndef EXCEPTIONDEFINE_H
    #define EXCEPTIONDEFINE_H

    //----------------------------------------------------------------//
    /* INCLUDE */

    /* type */
    #if __has_include(<generated_external_exception_header.hpp>)
        // Try to find the one generated by the user for it's own exception
        // Collision between external and internal will be handled in a way that external will be ignored
        #include <generated_external_exception_header.hpp>  // utils::exception::ExternalCode, utils::exception::ExternalMessages, utils::exception::ExternalInfo, utils::exception::ExternalRestriction
    #endif
    #if !__has_include("generated_internal_exception_header.hpp")
        // Minimal check if the file was build during the compilation
        #pragma message( \
            "\n\n" \
            "-----------------------------------------------------------------------\n" \
            "generated_internal_exception_header.hpp could not be found.\n" \
            "\n" \
            "Steps:\n" \
            "  1 - Check that you're using the latest release of libutils.\n" \
            "      (actual version: " __LIBUTILS_VERSION__ ")\n" \
            "  2 - Confirm this header still exists in the official repository\n" \
            "      (it may have been renamed or removed due to human error).\n" \
            "\n" \
            "If the problem persists (and wasn't already reported), open an issue at:\n" \
            "  https://github.com/TsukiNi22/libutils/issues\n" \
            "-----------------------------------------------------------------------\n\n" \
        )
        #error "generated_internal_exception_header.hpp not found - see message above"
    #endif
    // Keep the include even if it's doesn't exist to kill the compilation
    #include "generated_internal_exception_header.hpp"  // utils::exception::InternalCode, utils::exception::InternalMessages, utils::exception::InternalInfo, utils::exception::InternalRestriction
    #include <cstdint>                                  // std::uint8_t

    //----------------------------------------------------------------//
    /* DEFINE */
    
    /* Definition of the different return status */
    #ifndef OK
        #define OK 0 // Valid
    #endif
    #ifndef KO
        #define KO -1 // Error
    #endif

namespace utils::exception { // namespace start
//----------------------------------------------------------------//
/* TYPEDEF */

/* Definition of the different exception type */
enum Type: std::uint8_t {
    None    = 0b0001, // Exception like Exit, does nothing (ignore other type)
    Fatal   = 0b0010,
    Error   = 0b0100,
    Warning = 0b1000,
};

// ------------ Operator ---------- //
constexpr utils::exception::Type operator|(utils::exception::Type lhs, utils::exception::Type rhs)
{return static_cast<utils::exception::Type>(static_cast<std::uint8_t>(lhs) | static_cast<std::uint8_t>(rhs));}
constexpr utils::exception::Type operator&(utils::exception::Type lhs, utils::exception::Type rhs)
{return static_cast<utils::exception::Type>(static_cast<std::uint8_t>(lhs) & static_cast<std::uint8_t>(rhs));}
constexpr utils::exception::Type operator^(utils::exception::Type lhs, utils::exception::Type rhs)
{return static_cast<utils::exception::Type>(static_cast<std::uint8_t>(lhs) ^ static_cast<std::uint8_t>(rhs));}
constexpr utils::exception::Type operator~(utils::exception::Type f)
{return static_cast<utils::exception::Type>(~static_cast<std::uint8_t>(f));}

inline utils::exception::Type& operator|=(utils::exception::Type& lhs, utils::exception::Type rhs) {return lhs = lhs | rhs;}
inline utils::exception::Type& operator&=(utils::exception::Type& lhs, utils::exception::Type rhs) {return lhs = lhs & rhs;}
inline utils::exception::Type& operator^=(utils::exception::Type& lhs, utils::exception::Type rhs) {return lhs = lhs ^ rhs;}

} // namespace end
#endif /* EXCEPTIONDEFINE_H */
