
/**************************************************************\
Edition (auto):
##  --/--/---- by generate_exception_header.py

File Name:
##  @file generated_exception_header.hpp

File Description:
##  Header auto generated by the python script at compilation
##  Generated from the files in 'cmake/config/exceptions/'
##  Used for exception code & message definition
\**************************************************************/

#ifndef GENERATED_EXCEPTION_HEADER_H
    #define GENERATED_EXCEPTION_HEADER_H

    //----------------------------------------------------------------//
    /* INCLUDE */

    #include <iterator> // std::size
    #include <cstddef>  // std::size_t
    #include <cstdint>  // std::uint8_t

namespace utils::exception { // namespace start
//----------------------------------------------------------------//
/* TYPEDEF */

/* Definition of the different exception code */
enum class Code: std::size_t {
    Undefined = 0,
    Exit,
    Empty,
    UnknowId,
    UnknowKey,
    Override,
    Freezed,
    VectorInvalidIndex,
    ExceptionCodeRestriction,
    ANSIMouseEvent,
    IdOverflow,
    SharedObject,
    CliInternal,
    CliHook,
    CliParser,
    CliExecution,
    CliUndefined,
    CliAlreadyRunning,
    ArgumentsNumber,
    OptionIngored,
    UnknowFlag,
    NoCompliantUsage,
    ArgParserHook,
    OptionsNumber,
    FlagOptionsNumber,
    Option,
    FlagOption,
    FlagCombinaison,
    DuplicatedFlag,
    MiddlewareCall,
    CODE_SENTINEL // sentinel used for verification
};

/* Corresponding exception message for each code */
constexpr inline const char *Message[] = {
    /* Undefined */ "An undefined error has occured",
    /* Exit */ "Exit",
    /* Empty */ "Empty",
    /* UnknowId */ "Try to do thing with an unknow id",
    /* UnknowKey */ "Try to do thing with an unknow key",
    /* Override */ "The override is desactivated",
    /* Freezed */ "Can't edit a freezed things",
    /* VectorInvalidIndex */ "Invalid index on a vector",
    /* ExceptionCodeRestriction */ "Error during the setup of an exception",
    /* ANSIMouseEvent */ "Error during the read of the mouse event",
    /* IdOverflow */ "Can't distribute an id, uint32_t limits are reach",
    /* SharedObject */ "An object created with dynamic code that was free is still alive",
    /* CliInternal */ "Internal error from the cli",
    /* CliHook */ "Error during a hook call",
    /* CliParser */ "Error during the parsing",
    /* CliExecution */ "Error during the command execution",
    /* CliUndefined */ "An undefined error has append",
    /* CliAlreadyRunning */ "Can't start a cli that is already running",
    /* ArgumentsNumber */ "Invalid number of argument(s) given, use '-h' for more information",
    /* OptionIngored */ "Option ignored, can't determine it's ownership",
    /* UnknowFlag */ "Unknow flag",
    /* NoCompliantUsage */ "No compliant usage where found, use '-h' for more information",
    /* ArgParserHook */ "Error during an execution of hook",
    /* OptionsNumber */ "Invalid number of option(s) given, use '-h' for more information",
    /* FlagOptionsNumber */ "Invalid number of option(s) for the flag",
    /* Option */ "Invalid option, the parsing hook has failed",
    /* FlagOption */ "Invalid flag option, the parsing hook has failed",
    /* FlagCombinaison */ "Invalid flag combinaison",
    /* DuplicatedFlag */ "A flag was redefined, only the first will be used",
    /* MiddlewareCall */ "Error during a middleware call",
};

/* Potential default info: nullptr same as "[None]" */
constexpr inline const char *Info[] = {
    /* Undefined */ nullptr,
    /* Exit */ "Exit",
    /* Empty */ nullptr,
    /* UnknowId */ nullptr,
    /* UnknowKey */ nullptr,
    /* Override */ nullptr,
    /* Freezed */ nullptr,
    /* VectorInvalidIndex */ "Can't retrieve the value, the VectorX dosen't have this index",
    /* ExceptionCodeRestriction */ "Restriction trigerred on a code & type combination",
    /* ANSIMouseEvent */ nullptr,
    /* IdOverflow */ nullptr,
    /* SharedObject */ nullptr,
    /* CliInternal */ nullptr,
    /* CliHook */ nullptr,
    /* CliParser */ nullptr,
    /* CliExecution */ nullptr,
    /* CliUndefined */ nullptr,
    /* CliAlreadyRunning */ nullptr,
    /* ArgumentsNumber */ nullptr,
    /* OptionIngored */ nullptr,
    /* UnknowFlag */ nullptr,
    /* NoCompliantUsage */ nullptr,
    /* ArgParserHook */ nullptr,
    /* OptionsNumber */ nullptr,
    /* FlagOptionsNumber */ nullptr,
    /* Option */ nullptr,
    /* FlagOption */ nullptr,
    /* FlagCombinaison */ nullptr,
    /* DuplicatedFlag */ nullptr,
    /* MiddlewareCall */ nullptr,
};

/* Potential restriction on exception code */
// 0b0000 = no restriction	(allow all)
// 0b0001 = None			(allow None)
// 0b0010 = Fatal			(allow Fatal)
// 0b0100 = Error			(allow Error)
// 0b1000 = Warning			(allow Warning)
constexpr inline const std::uint8_t Restriction[] = {
    /* Undefined */ 0b0000, // allow: All
    /* Exit */ 0b0001, // allow: None
    /* Empty */ 0b0000, // allow: All
    /* UnknowId */ 0b1110, // allow: Fatal, Error, Warning
    /* UnknowKey */ 0b1110, // allow: Fatal, Error, Warning
    /* Override */ 0b1110, // allow: Fatal, Error, Warning
    /* Freezed */ 0b1110, // allow: Fatal, Error, Warning
    /* VectorInvalidIndex */ 0b1110, // allow: Fatal, Error, Warning
    /* ExceptionCodeRestriction */ 0b0110, // allow: Fatal, Error
    /* ANSIMouseEvent */ 0b0110, // allow: Fatal, Error
    /* IdOverflow */ 0b0110, // allow: Fatal, Error
    /* SharedObject */ 0b1110, // allow: Fatal, Error, Warning
    /* CliInternal */ 0b0110, // allow: Fatal, Error
    /* CliHook */ 0b1110, // allow: Fatal, Error, Warning
    /* CliParser */ 0b0000, // allow: All
    /* CliExecution */ 0b0110, // allow: Fatal, Error
    /* CliUndefined */ 0b0110, // allow: Fatal, Error
    /* CliAlreadyRunning */ 0b1110, // allow: Fatal, Error, Warning
    /* ArgumentsNumber */ 0b0110, // allow: Fatal, Error
    /* OptionIngored */ 0b1110, // allow: Fatal, Error, Warning
    /* UnknowFlag */ 0b1110, // allow: Fatal, Error, Warning
    /* NoCompliantUsage */ 0b0110, // allow: Fatal, Error
    /* ArgParserHook */ 0b0110, // allow: Fatal, Error
    /* OptionsNumber */ 0b0110, // allow: Fatal, Error
    /* FlagOptionsNumber */ 0b0110, // allow: Fatal, Error
    /* Option */ 0b1110, // allow: Fatal, Error, Warning
    /* FlagOption */ 0b1110, // allow: Fatal, Error, Warning
    /* FlagCombinaison */ 0b1110, // allow: Fatal, Error, Warning
    /* DuplicatedFlag */ 0b1110, // allow: Fatal, Error, Warning
    /* MiddlewareCall */ 0b1110, // allow: Fatal, Error, Warning
};

// Check at the compile time the correspondece between the message & code
static_assert(std::size(Message) == static_cast<std::size_t>(utils::exception::Code::CODE_SENTINEL), "The message array doesn't correspond to the available exception codes");
static_assert(std::size(Info) == static_cast<std::size_t>(utils::exception::Code::CODE_SENTINEL), "The info array doesn't correspond to the available exception codes");
static_assert(std::size(Restriction) == static_cast<std::size_t>(utils::exception::Code::CODE_SENTINEL), "The restriction array doesn't correspond to the available exception codes");

} // namespace end
#endif /* GENERATED_EXCEPTION_HEADER_H */
