
/**************************************************************\
Edition (auto):
##  --/--/---- by generate_exception_header.py

File Name:
##  @file generated_internal_exception_header.hpp

File Description:
##  Header auto generated by the python script at compilation
##  Generated from the files in 'cmake/config/exceptions/'
##  Used for exception code & message definition
\**************************************************************/

#ifndef INTERNAL_GENERATED_INTERNAL_EXCEPTION_HEADER_H
    #define INTERNAL_GENERATED_INTERNAL_EXCEPTION_HEADER_H

    //----------------------------------------------------------------//
    /* INCLUDE */

    #include <unordered_map>    // std::unordered_map
    #include <iterator>         // std::size
    #include <cstddef>          // std::size_t
    #include <cstdint>          // std::uint8_t

namespace utils::exception { // namespace start
//----------------------------------------------------------------//
/* TYPEDEF */

/* Definition of the different exception code */
enum class InternalCode: std::size_t {
    Undefined = 0,
    Exit = 15095367374592363379ull,
    Empty = 14321610350218508748ull,
    UndefinedCall = 3359234434991996320ull,
    UnauthorizedCall = 14424815468256430437ull,
    InvalidArgument = 3345669790923938179ull,
    UnknowId = 4263289034106755386ull,
    UnknowKey = 12334043516309347137ull,
    Override = 4880793000083787920ull,
    OutOfBounds = 3389359889948621131ull,
    Freezed = 2508248173660191566ull,
    BadCast = 16151812791444123020ull,
    UnknowCast = 6680257745859723252ull,
    CliTTY = 7532242402519323293ull,
    CliInternal = 12564791026278379151ull,
    CliHook = 13081330417418057012ull,
    CliParser = 12964789185312968338ull,
    CliExecution = 4618793667853650974ull,
    CliUndefined = 6899293127811735148ull,
    CliAlreadyRunning = 1182638627334015411ull,
    CliKilled = 13835053808356336641ull,
    ArgumentsNumber = 7876789757338490523ull,
    OptionIngored = 11084392326436070358ull,
    UnknowFlag = 1888382847103148552ull,
    NoCompliantUsage = 4261266083679998998ull,
    ArgParserHook = 4700046732834365152ull,
    OptionsNumber = 17652397889544614484ull,
    FlagOptionsNumber = 8992712080362871110ull,
    Option = 5020014651646256745ull,
    FlagOption = 7286571616319965473ull,
    FlagCombinaison = 3465342320065814886ull,
    DuplicatedFlag = 1484916767978747442ull,
    ExceptionCodeRestriction = 13879425725543769625ull,
    MiddlewareCall = 13499662014297344931ull,
    VectorInvalidIndex = 9996010333556084833ull,
    IdOverflow = 8610564673716166394ull,
    SharedObject = 4197965883596487577ull,
    ANSIMouseEvent = 15574262374879664887ull,
    Codec = 16250259813861694288ull,
    InvalidCodec = 6830493561145259002ull,
};

/* Corresponding exception message for each code */
inline const std::unordered_map<utils::exception::InternalCode, const char*> InternalMessages = {
    {utils::exception::InternalCode::Undefined, "An undefined error has occured"},
    {utils::exception::InternalCode::Exit, "Exit"},
    {utils::exception::InternalCode::Empty, "Empty"},
    {utils::exception::InternalCode::UndefinedCall, "This function is not defined and was left as-is"},
    {utils::exception::InternalCode::UnauthorizedCall, "Can't allow the call to this function"},
    {utils::exception::InternalCode::InvalidArgument, "Invalid argument value"},
    {utils::exception::InternalCode::UnknowId, "Try to do thing with an unknow id"},
    {utils::exception::InternalCode::UnknowKey, "Try to do thing with an unknow key"},
    {utils::exception::InternalCode::Override, "The override is desactivated"},
    {utils::exception::InternalCode::OutOfBounds, "Bounds have been oversteapaded"},
    {utils::exception::InternalCode::Freezed, "Can't edit a freezed things"},
    {utils::exception::InternalCode::BadCast, "Invalid cast between from a type to another"},
    {utils::exception::InternalCode::UnknowCast, "Unknow cast type, can't proceed"},
    {utils::exception::InternalCode::CliTTY, "Can't start cli, not in a tty (enable the flag TTY to force usage)"},
    {utils::exception::InternalCode::CliInternal, "Internal error from the cli"},
    {utils::exception::InternalCode::CliHook, "Error during a hook call"},
    {utils::exception::InternalCode::CliParser, "Error during the parsing"},
    {utils::exception::InternalCode::CliExecution, "Error during the command execution"},
    {utils::exception::InternalCode::CliUndefined, "An undefined error has append"},
    {utils::exception::InternalCode::CliAlreadyRunning, "Can't start a cli that is already running"},
    {utils::exception::InternalCode::CliKilled, "Can't start or restart a cli that was killed"},
    {utils::exception::InternalCode::ArgumentsNumber, "Invalid number of argument(s) given, use '-h' for more information"},
    {utils::exception::InternalCode::OptionIngored, "Option ignored, can't determine it's ownership"},
    {utils::exception::InternalCode::UnknowFlag, "Unknow flag"},
    {utils::exception::InternalCode::NoCompliantUsage, "No compliant usage where found, use '-h' for more information"},
    {utils::exception::InternalCode::ArgParserHook, "Error during an execution of hook"},
    {utils::exception::InternalCode::OptionsNumber, "Invalid number of option(s) given, use '-h' for more information"},
    {utils::exception::InternalCode::FlagOptionsNumber, "Invalid number of option(s) for the flag"},
    {utils::exception::InternalCode::Option, "Invalid option, the parsing hook has failed"},
    {utils::exception::InternalCode::FlagOption, "Invalid flag option, the parsing hook has failed"},
    {utils::exception::InternalCode::FlagCombinaison, "Invalid flag combinaison"},
    {utils::exception::InternalCode::DuplicatedFlag, "A flag was redefined, only the first will be used"},
    {utils::exception::InternalCode::ExceptionCodeRestriction, "Error during the setup of an exception"},
    {utils::exception::InternalCode::MiddlewareCall, "Error during a middleware call"},
    {utils::exception::InternalCode::VectorInvalidIndex, "Invalid index on a vector"},
    {utils::exception::InternalCode::IdOverflow, "Can't distribute an id, uint32_t limits are reach"},
    {utils::exception::InternalCode::SharedObject, "An object created with dynamic code that was free is still alive"},
    {utils::exception::InternalCode::ANSIMouseEvent, "Error during the read of the mouse event"},
    {utils::exception::InternalCode::Codec, "Error during the encoding/decoding of the given string"},
    {utils::exception::InternalCode::InvalidCodec, "The given codec is invalid and can't be used for the task"},
};

/* Potential default info: nullptr same as "[None]" */
inline const std::unordered_map<utils::exception::InternalCode, const char*> InternalInfo = {
    {utils::exception::InternalCode::Undefined, nullptr},
    {utils::exception::InternalCode::Exit, "Exit"},
    {utils::exception::InternalCode::Empty, nullptr},
    {utils::exception::InternalCode::UndefinedCall, nullptr},
    {utils::exception::InternalCode::UnauthorizedCall, nullptr},
    {utils::exception::InternalCode::InvalidArgument, nullptr},
    {utils::exception::InternalCode::UnknowId, nullptr},
    {utils::exception::InternalCode::UnknowKey, nullptr},
    {utils::exception::InternalCode::Override, nullptr},
    {utils::exception::InternalCode::OutOfBounds, nullptr},
    {utils::exception::InternalCode::Freezed, nullptr},
    {utils::exception::InternalCode::BadCast, nullptr},
    {utils::exception::InternalCode::UnknowCast, nullptr},
    {utils::exception::InternalCode::CliTTY, nullptr},
    {utils::exception::InternalCode::CliInternal, nullptr},
    {utils::exception::InternalCode::CliHook, nullptr},
    {utils::exception::InternalCode::CliParser, nullptr},
    {utils::exception::InternalCode::CliExecution, nullptr},
    {utils::exception::InternalCode::CliUndefined, nullptr},
    {utils::exception::InternalCode::CliAlreadyRunning, nullptr},
    {utils::exception::InternalCode::CliKilled, nullptr},
    {utils::exception::InternalCode::ArgumentsNumber, nullptr},
    {utils::exception::InternalCode::OptionIngored, nullptr},
    {utils::exception::InternalCode::UnknowFlag, nullptr},
    {utils::exception::InternalCode::NoCompliantUsage, nullptr},
    {utils::exception::InternalCode::ArgParserHook, nullptr},
    {utils::exception::InternalCode::OptionsNumber, nullptr},
    {utils::exception::InternalCode::FlagOptionsNumber, nullptr},
    {utils::exception::InternalCode::Option, nullptr},
    {utils::exception::InternalCode::FlagOption, nullptr},
    {utils::exception::InternalCode::FlagCombinaison, nullptr},
    {utils::exception::InternalCode::DuplicatedFlag, nullptr},
    {utils::exception::InternalCode::ExceptionCodeRestriction, "Restriction trigerred on a code & type combination"},
    {utils::exception::InternalCode::MiddlewareCall, nullptr},
    {utils::exception::InternalCode::VectorInvalidIndex, "Can't retrieve the value, the VectorX dosen't have this index"},
    {utils::exception::InternalCode::IdOverflow, nullptr},
    {utils::exception::InternalCode::SharedObject, nullptr},
    {utils::exception::InternalCode::ANSIMouseEvent, nullptr},
    {utils::exception::InternalCode::Codec, nullptr},
    {utils::exception::InternalCode::InvalidCodec, nullptr},
};

/* Potential restriction on exception code */
// 0b0000 = no restriction	(allow all)
// 0b0001 = None			(allow None)
// 0b0010 = Fatal			(allow Fatal)
// 0b0100 = Error			(allow Error)
// 0b1000 = Warning			(allow Warning)
inline const std::unordered_map<utils::exception::InternalCode, const std::uint8_t> InternalRestriction = {
    {utils::exception::InternalCode::Undefined, 0b0000}, // allow: All
    {utils::exception::InternalCode::Exit, 0b0001}, // allow: None
    {utils::exception::InternalCode::Empty, 0b0000}, // allow: All
    {utils::exception::InternalCode::UndefinedCall, 0b0110}, // allow: Fatal, Error
    {utils::exception::InternalCode::UnauthorizedCall, 0b0110}, // allow: Fatal, Error
    {utils::exception::InternalCode::InvalidArgument, 0b1110}, // allow: Fatal, Error, Warning
    {utils::exception::InternalCode::UnknowId, 0b1110}, // allow: Fatal, Error, Warning
    {utils::exception::InternalCode::UnknowKey, 0b1110}, // allow: Fatal, Error, Warning
    {utils::exception::InternalCode::Override, 0b1110}, // allow: Fatal, Error, Warning
    {utils::exception::InternalCode::OutOfBounds, 0b1110}, // allow: Fatal, Error, Warning
    {utils::exception::InternalCode::Freezed, 0b1110}, // allow: Fatal, Error, Warning
    {utils::exception::InternalCode::BadCast, 0b0110}, // allow: Fatal, Error
    {utils::exception::InternalCode::UnknowCast, 0b0110}, // allow: Fatal, Error
    {utils::exception::InternalCode::CliTTY, 0b0110}, // allow: Fatal, Error
    {utils::exception::InternalCode::CliInternal, 0b0110}, // allow: Fatal, Error
    {utils::exception::InternalCode::CliHook, 0b1110}, // allow: Fatal, Error, Warning
    {utils::exception::InternalCode::CliParser, 0b0000}, // allow: All
    {utils::exception::InternalCode::CliExecution, 0b0110}, // allow: Fatal, Error
    {utils::exception::InternalCode::CliUndefined, 0b0110}, // allow: Fatal, Error
    {utils::exception::InternalCode::CliAlreadyRunning, 0b1110}, // allow: Fatal, Error, Warning
    {utils::exception::InternalCode::CliKilled, 0b1110}, // allow: Fatal, Error, Warning
    {utils::exception::InternalCode::ArgumentsNumber, 0b0110}, // allow: Fatal, Error
    {utils::exception::InternalCode::OptionIngored, 0b1110}, // allow: Fatal, Error, Warning
    {utils::exception::InternalCode::UnknowFlag, 0b1110}, // allow: Fatal, Error, Warning
    {utils::exception::InternalCode::NoCompliantUsage, 0b0110}, // allow: Fatal, Error
    {utils::exception::InternalCode::ArgParserHook, 0b0110}, // allow: Fatal, Error
    {utils::exception::InternalCode::OptionsNumber, 0b0110}, // allow: Fatal, Error
    {utils::exception::InternalCode::FlagOptionsNumber, 0b0110}, // allow: Fatal, Error
    {utils::exception::InternalCode::Option, 0b1110}, // allow: Fatal, Error, Warning
    {utils::exception::InternalCode::FlagOption, 0b1110}, // allow: Fatal, Error, Warning
    {utils::exception::InternalCode::FlagCombinaison, 0b1110}, // allow: Fatal, Error, Warning
    {utils::exception::InternalCode::DuplicatedFlag, 0b1110}, // allow: Fatal, Error, Warning
    {utils::exception::InternalCode::ExceptionCodeRestriction, 0b0110}, // allow: Fatal, Error
    {utils::exception::InternalCode::MiddlewareCall, 0b1110}, // allow: Fatal, Error, Warning
    {utils::exception::InternalCode::VectorInvalidIndex, 0b1110}, // allow: Fatal, Error, Warning
    {utils::exception::InternalCode::IdOverflow, 0b0110}, // allow: Fatal, Error
    {utils::exception::InternalCode::SharedObject, 0b1110}, // allow: Fatal, Error, Warning
    {utils::exception::InternalCode::ANSIMouseEvent, 0b0110}, // allow: Fatal, Error
    {utils::exception::InternalCode::Codec, 0b0110}, // allow: Fatal, Error
    {utils::exception::InternalCode::InvalidCodec, 0b1110}, // allow: Fatal, Error, Warning
};

// Check at the compile time the correspondece between the message & code
/*
static_assert(std::size(InternalMessages) == static_cast<std::size_t>(utils::exception::InternalCode::CODE_SENTINEL), "The message array doesn't correspond to the available exception codes");
static_assert(std::size(InternalInfo) == static_cast<std::size_t>(utils::exception::InternalCode::CODE_SENTINEL), "The info array doesn't correspond to the available exception codes");
static_assert(std::size(InternalRestriction) == static_cast<std::size_t>(utils::exception::InternalCode::CODE_SENTINEL), "The restriction array doesn't correspond to the available exception codes");
*/

} // namespace end
#endif /* INTERNAL_GENERATED_INTERNAL_EXCEPTION_HEADER_H */
